CREATE PROCEDURE [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].[test Only New SKs Added]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].ACTUAL') IS NOT NULL DROP TABLE [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].ACTUAL;
	IF OBJECT_ID('[dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].EXPECTED') IS NOT NULL DROP TABLE [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].EXPECTED;

	EXECUTE tSQLt.FakeTable @TableName = '[dimensionSchema].templateDimCoreName_Dim';
	EXECUTE tSQLt.FakeTable @TableName = '[dimensionRpSchema].templateDimCoreName_dim_dimRpName';
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 1;
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 2;
	
	EXECUTE [dimensionRpSchema].[templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp];
	
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 3;
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 4;
	
	--ACT
	EXECUTE [dimensionRpSchema].[templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp];
	
	SELECT 
	[SK_templateDimCoreName]
	INTO [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].ACTUAL
	FROM [dimensionRpSchema].[templateDimCoreName_dim_dimRpName];

	--ASSERT
	CREATE TABLE [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].EXPECTED (
		[SK_templateDimCoreName] INT
	);
	INSERT INTO [dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].EXPECTED (
		[SK_templateDimCoreName]
	) VALUES (1),(2),(3),(4);

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].EXPECTED', @Actual = '[dimensionRpSchema__templateDimCoreName_dim_dimRpName_Synchronize_Step1_GetSKs_usp].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
